before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
  - sudo apt-get install libpcap-dev
install:
  - sudo apt-get install rust-nightly
script:
  - rustc lib.rs
